import type { Metadata } from "next";
import { sitePath } from "../../lib/paths";

export const metadata: Metadata = {
  title: "Codes, models & algorithms",
  description: "Computational tools, cosmology notebooks, models and reconstruction algorithms developed by Dhiraj Kumar Hazra.",
};

const notebookRoot = "https://gitlab.com/dhirajhazra/simple-codes-in-cosmology/-/blob/master";

const notebooks = [
  { number: "01", title: "Age of the Universe", text: "Friedmann equations; compute the age of the Universe.", href: `${notebookRoot}/Age-of-the-Universe.ipynb` },
  { number: "02", title: "Ages, distances & angles", text: "Expansion rate; age at redshift z; comoving, angular-diameter and luminosity distances; cosmic acceleration.", href: `${notebookRoot}/Ages-Distances-Angles.ipynb` },
  { number: "03", title: "ΛCDM constraints", text: "Supernovae; distance modulus; χ²; best fit; Markov-chain Monte Carlo and parameter constraints.", href: `${notebookRoot}/Dark-Energy-Density-LCDM-Constraints.ipynb` },
  { number: "04", title: "Dark-energy models", text: "Variable equations of state; scalar fields; CPL and decaying-dark-energy parametrizations; BAO, CMB summary statistics and inference.", href: `${notebookRoot}/Dark-Energy-Models-Parametrizations.ipynb` },
  { number: "05", title: "Reionization", text: "The tanh model; optical depth; neutral hydrogen; CMB signatures and constraints.", href: `${notebookRoot}/Reionization.ipynb` },
  { number: "06", title: "Inflation & primordial perturbations", text: "Horizon problem; Klein–Gordon and Mukhanov–Sasaki equations; scalar and tensor spectra; slow-roll comparison.", href: `${notebookRoot}/Inflation-Primordial-Perturbation.ipynb` },
  { number: "07", title: "Mini-code: FIRAS spectrum", text: "Fit the CMB monopole and constrain spectral distortions using FIRAS data.", href: `${notebookRoot}/mini-codes/Fitting-FIRAS-data.ipynb` },
];

const notebookFigures = [
  {
    label: "Distance measures",
    src: "/figures/codes/cosmological-distances.png",
    alt: "Angular-diameter, luminosity and comoving distances as functions of redshift",
    caption: "Angular-diameter, luminosity and comoving distances across redshift.",
    href: `${notebookRoot}/Ages-Distances-Angles.ipynb`,
  },
  {
    label: "ΛCDM inference",
    src: "/figures/codes/lcdm-constraints.png",
    alt: "Posterior constraints on matter density and the Hubble constant",
    caption: "An MCMC posterior for Ωm and H₀ from the supernova exercise.",
    href: `${notebookRoot}/Dark-Energy-Density-LCDM-Constraints.ipynb`,
  },
  {
    label: "Inflation",
    src: "/figures/codes/inflation-spectra.png",
    alt: "Numerical and slow-roll scalar and tensor primordial power spectra",
    caption: "Numerical scalar and tensor spectra compared with slow-roll forms.",
    href: `${notebookRoot}/Inflation-Primordial-Perturbation.ipynb`,
  },
  {
    label: "FIRAS mini-code",
    src: "/figures/codes/firas-residuals.png",
    alt: "FIRAS residual intensity measurements as a function of frequency",
    caption: "Residual intensity after fitting the CMB blackbody spectrum.",
    href: `${notebookRoot}/mini-codes/Fitting-FIRAS-data.ipynb`,
  },
];

const researchCodes = [
  ["BINGO", "Public / Fortran 90", "Computes the scalar power spectrum, bispectrum and fNL for arbitrary triangular configurations in canonical single-field inflation.", "/codes/bingo"],
  ["PPS Code Suite", "Research", "Exact primordial spectra for canonical and non-canonical single-field models, two-field isocurvature and correlation spectra, and tensor modes; used as a CosmoMC add-on.", null],
  ["Halo Formation", "Research", "Number density and formation rates of dark-matter halos for arbitrary inflationary potentials using Press–Schechter and Sheth–Tormen formalisms.", null],
  ["PBH + SGWB", "Research", "Primordial-black-hole abundance and the stochastic gravitational-wave background generated by enhanced small-scale primordial power.", null],
  ["Fluid Simulation", "In development", "A 3D dark-matter fluid simulation in a horizon-size box, developed with Stephen Appleby.", null],
  ["Lyman-α Continuum", "Research", "Continuum estimation in redshifted quasar spectra for extracting neutral-hydrogen absorption and flux correlations.", null],
  ["Semi-analytical Reionization", "Fortran 90", "Reionization optical depth from a nonlinear matter-density field; developed for work on Lyman-α constraints.", null],
  ["ELiXSIR", "Public / Epidemiology", "A nine-compartment, age-stratified and migration-linked model used in a published district-to-national analysis of India’s first COVID-19 wave.", "/codes/elixsir"],
];

const models = [
  ["Wiggly Whipped Inflation", "A family of inflationary potentials producing large-scale suppression and localized oscillations supported in parts of the Planck likelihood. The framework followed Whipped Inflation and has been tested against CMB and LSS forecasts."],
  ["Poly-Reion", "A flexible, physical history constructed from free-electron fractions at selected redshifts and polynomial interpolation. It was introduced with Planck 2015 constraints and adapted in the Planck 2018 reionization analysis."],
  ["Reionization Reconstruction", "A free-form solution of ionization equations in which source and sink terms are inferred jointly from CMB, UV-luminosity-density and neutral-hydrogen data. The reconstruction finds a duration near three redshift units and constrains recombination timescales."],
];

const algorithms = [
  ["Modified Richardson–Lucy", "Extends deconvolution of the primordial spectrum to combined binned and unbinned CMB spectra, including foreground and lensing effects; supplied as CAMB and CosmoMC add-ons."],
  ["Optimized PPS binning", "Locates broad features with a compact set of flexible bins. Applied to Planck, it showed where the data require a red spectral tilt."],
  ["3D Lyman-α / 21 cm bispectrum", "Uses the auto- and cross-bispectra of Lyman-α transmitted flux and post-reionization 21 cm signal to constrain primordial non-Gaussianity."],
  ["Isotropy with quasar spectroscopy", "Tests cosmic isotropy in the matter-dominated epoch using moments of the transmitted-flux distribution in BOSS DR9 sky patches."],
];

export default function CodesPage() {
  return (
    <main id="main">
      <header className="page-intro page-intro--compact shell">
        <p className="kicker">Computational notebook</p>
        <h1>Codes, models<br />&amp; algorithms.</h1>
        <div className="page-intro__actions">
          <a className="text-link" href="https://gitlab.com/dhirajhazra/simple-codes-in-cosmology/-/tree/master">Teaching notebooks on GitLab ↗</a>
        </div>
      </header>

      <section className="manifesto shell">
        <p className="kicker">Cosmological scales</p>
        <div className="manifesto__body">
          <p className="manifesto__lead">
            Cosmology has one observable Universe. We see it at many wavelengths,
            resolutions, directions and look-back times—not through repeatable experiments.
          </p>
          <p>
            Redshift z measures the stretching of light by expansion: z = 0 here and now,
            while distant objects are seen at earlier epochs. Given the matter and dark-energy
            densities and H₀, the Friedmann equations map redshift into distance and age. The
            resulting history runs from inflation through radiation and matter domination to
            today’s accelerated expansion.
          </p>
          <p>
            This makes numerical model comparison and model-independent reconstruction
            indispensable partners. The tools below solve theories, reconstruct signals and
            connect them to observations.
          </p>
        </div>
      </section>

      <section className="notebook-section shell" id="teaching-notebooks">
        <div className="section-heading section-heading--rule">
          <p className="kicker">For MSc &amp; PhD students</p>
          <h2>Codes in cosmology</h2>
        </div>
        <div className="notebook-grid">
          {notebooks.map((notebook) => (
            <a
              className="notebook-entry"
              href={notebook.href}
              key={notebook.number}
              rel="noreferrer"
              target="_blank"
            >
              <span>{notebook.number}</span>
              <h3>{notebook.title}</h3>
              <p>{notebook.text}</p>
              <b>Open notebook ↗</b>
            </a>
          ))}
        </div>
        <div className="notebook-figures" id="notebook-output">
          {notebookFigures.map((figure, index) => (
            <a href={figure.href} key={figure.label} rel="noreferrer" target="_blank">
              <figure>
                <div className="notebook-figure__meta"><span>OUTPUT / {String(index + 1).padStart(2, "0")}</span><span>{figure.label}</span></div>
                <div className="notebook-figure__image"><img src={sitePath(figure.src)} alt={figure.alt} /></div>
                <figcaption>{figure.caption} <span>Open notebook ↗</span></figcaption>
              </figure>
            </a>
          ))}
        </div>
      </section>

      <section className="tool-ledger shell">
        <div className="section-heading section-heading--rule">
          <p className="kicker">Research software</p>
          <h2>Numerical codes</h2>
        </div>
        <div className="ledger">
          {researchCodes.map(([name, status, text, href], index) => (
            <article className="ledger-row" key={name}>
              <span className="ledger-row__number">{String(index + 1).padStart(2, "0")}</span>
              <div><h3>{name}</h3><p>{text}</p></div>
              <div className="ledger-row__status">
                <span>{status}</span>
                {href && <a href={sitePath(href)}>Open dossier →</a>}
              </div>
            </article>
          ))}
        </div>
      </section>

      <section className="split-ledgers shell">
        <div>
          <div className="section-heading section-heading--rule"><p className="kicker">Theory constructions</p><h2>Models</h2></div>
          {models.map(([name, text]) => <article className="prose-entry" key={name}><h3>{name}</h3><p>{text}</p></article>)}
        </div>
        <div>
          <div className="section-heading section-heading--rule"><p className="kicker">Inverse problems</p><h2>Algorithms</h2></div>
          {algorithms.map(([name, text]) => <article className="prose-entry" key={name}><h3>{name}</h3><p>{text}</p></article>)}
        </div>
      </section>
    </main>
  );
}
