import type { Metadata } from "next";
import { sitePath } from "../../lib/paths";

export const metadata: Metadata = {
  title: "Research",
  description: "Research spanning inflation, cosmological inference, reionization, large-scale structure and interdisciplinary statistical modelling.",
};

const sections = [
  {
    id: "early-universe",
    number: "01",
    eyebrow: "Inflation · primordial features · non-Gaussianity",
    title: "The early Universe",
    text: [
      "I work on inflationary models and the primordial perturbations they generate. A recurring question is whether localized departures from a smooth primordial spectrum—suppression, oscillations or other features—can illuminate the dynamics of inflation.",
      "This includes exact numerical solutions of scalar and tensor perturbations, two-field models, primordial black-hole formation, stochastic gravitational waves and the bispectrum. Whipped Inflation, Wiggly Whipped Inflation and the BINGO code grew out of this programme.",
    ],
    image: "/figures/research/wwi-feature-atlas.png",
    alt: "Four classes of primordial power-spectrum features generated by Wiggly Whipped Inflation",
    caption: "A feature atlas from Wiggly Whipped Inflation: suppression, localized structure, extended oscillations and mixed signatures.",
    paper: "https://arxiv.org/abs/1605.02106",
    source: "JCAP 2016",
    supplementaryFigures: [
      {
        label: "FIG. 01A",
        title: "Across detector windows",
        image: "/figures/research/sgwb-detector-windows.png",
        alt: "Predicted stochastic gravitational-wave spectra across pulsar timing, space-based and terrestrial detector windows",
        caption: "Predicted stochastic gravitational-wave spectra from a two-field inflation model, shown against sensitivity windows from pulsar timing arrays to terrestrial interferometers.",
        paper: "https://arxiv.org/abs/2005.02895",
        source: "JCAP 2020",
      },
      {
        label: "FIG. 01B",
        title: "Bispectrum over triangle space",
        image: "/figures/research/bingo-bispectrum.png",
        alt: "BINGO numerical result for the non-Gaussianity parameter over triangular wave-vector configurations",
        caption: "The numerical BINGO result for the non-Gaussianity parameter across allowed triangular wave-vector configurations in quadratic inflation.",
        paper: "https://arxiv.org/abs/1201.0926",
        source: "JCAP 2013",
      },
    ],
    cta: "Related publications →",
    ctaHref: "/publications",
  },
  {
    id: "inference",
    number: "02",
    eyebrow: "CMB · inverse problems · parameter estimation",
    title: "Cosmological inference",
    text: [
      "Model comparison and reconstruction are complementary. I develop statistical methods that reconstruct primordial physics directly from cosmological observations, then use those hints to build and test models.",
      "The work spans modified Richardson–Lucy deconvolution, optimized free-form binning, Gaussian processes and Bayesian parameter estimation. Recent analyses examine the Planck–ACT discordance and how different CMB datasets map onto the primordial spectrum.",
    ],
    image: "/figures/research/planck-act-reconstruction.png",
    alt: "Primordial power spectrum reconstructions from Planck and ACT",
    caption: "Free-form reconstructions show where Planck PR3 and ACT DR4 prefer different primordial structure.",
    paper: "https://arxiv.org/abs/2406.06296",
    source: "JCAP 2024",
    supplementaryFigures: [
      {
        label: "FIG. 02A",
        title: "Primordial power spectrum from Planck",
        image: "/figures/research/planck-pps-2014.png",
        alt: "Smooth primordial power spectra reconstructed from Planck temperature data compared with the best-fit power law",
        caption: "Uniform and error-weighted reconstructions isolate the broad and local structure preferred by Planck temperature data over a featureless power law.",
        paper: "https://arxiv.org/abs/1406.4827",
        source: "JCAP 2014",
      },
      {
        label: "FIG. 02B",
        title: "Reconstructed PPS and angular spectra",
        image: "/figures/research/planck-pps-cl-reconstruction.png",
        alt: "Color-coded Planck primordial power-spectrum reconstructions and their corresponding CMB temperature angular power spectra",
        caption: "Colour traces the improvement in Planck likelihood across the reconstruction: each primordial spectrum is paired with its predicted CMB temperature spectrum and residuals.",
        paper: "https://arxiv.org/abs/1406.4827",
        source: "JCAP 2014",
      },
    ],
    cta: "Related publications →",
    ctaHref: "/publications",
  },
  {
    id: "reionization",
    number: "03",
    eyebrow: "Cosmic dawn · ionization history · neutral hydrogen",
    title: "Reionization",
    text: [
      "Reionization connects the first luminous sources with the CMB and the intergalactic medium. I combine CMB optical depth, UV luminosity density and neutral-hydrogen observations to reconstruct this history with as few imposed shapes as possible.",
      "Poly-Reion provides flexible, physical histories; other work reconstructs the source and sink terms of the ionization equation and applies Gaussian processes to the evolving ionized fraction.",
    ],
    image: "/figures/research/reionization-history.png",
    alt: "Reconstructed ionized fraction of hydrogen across redshift from CMB and astrophysical observations",
    caption: "Free-form reionization histories jointly constrained by CMB polarization, UV luminosity density and neutral-hydrogen data.",
    paper: "https://arxiv.org/abs/1904.01547",
    source: "Physical Review Letters 2020",
    supplementaryFigures: [
      {
        label: "FIG. 03A",
        title: "UV luminosity-function fit at z = 4",
        image: "/figures/research/adak-uv-luminosity-function.png",
        alt: "Galaxy ultraviolet luminosity-function data at redshift four with Schechter and Gaussian-process fits",
        caption: "The Gaussian-process fit follows the observed bright-galaxy excess that the Schechter form misses; the blue and orange curves show posterior samples of the two fits.",
        paper: "https://arxiv.org/abs/2405.10180",
        source: "JCAP 2024",
      },
    ],
    cta: "Related publications →",
    ctaHref: "/publications",
  },
  {
    id: "structure",
    number: "04",
    eyebrow: "Galaxy clustering · EFTofLSS · primordial features",
    title: "Large-scale structure",
    text: [
      "The late-time matter distribution carries a transformed record of primordial physics. I study how inflationary features propagate through nonlinear evolution into galaxy clustering and halo abundance.",
      "The programme includes Lyman-α forest statistics and isotropy tests across survey footprints, halo formation, fluid and N-body simulations, and effective-field-theory modelling of large-scale structure, with connections to Euclid and future surveys.",
    ],
    image: "/figures/large-scale-structure.png",
    alt: "Linear and logarithmic primordial features evolved with linear theory, effective field theory, infrared resummation and N-body calculations",
    caption: "Primordial-feature signals evolved to redshift zero: one-loop EFTofLSS with infrared resummation closely tracks the N-body fit.",
    paper: "https://arxiv.org/abs/2504.06183",
    source: "Calderón et al. 2025",
    supplementaryFigures: [],
    cta: "Related publications →",
    ctaHref: "/publications",
  },
  {
    id: "epidemiology",
    number: "05",
    eyebrow: "Epidemiology · Bayesian inference · public-health data",
    title: "Interdisciplinary inference",
    text: [
      "I also adapt the numerical solvers, model comparison and Bayesian inference machinery of cosmology to problems outside the field. ELiXSIR is a fast Fortran extended, zone-linked nine-compartment epidemic solver with age-structured contacts, policy transitions and migration between regions.",
      "In the published INDSCI-SIM study, the framework was applied not only to Delhi, but across Karnataka districts and state, Bengaluru, Chennai, Mumbai, Pune and India as a whole. Joint fits to infections and deaths reconstructed reporting bias, infection fatality ratios and the evolving reproduction number.",
    ],
    image: "/figures/research/elixsir-india.png",
    alt: "ELiXSIR analysis of Karnataka COVID-19 cases, deaths, total infections, reporting bias, fatality ratio and reproduction number",
    caption: "Data, posterior bands and inferred epidemic quantities for Karnataka—one component of the multi-scale India study by Hazra et al. (2022, CC BY).",
    paper: "https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010632",
    source: "PLOS Computational Biology 2022",
    supplementaryFigures: [],
    cta: "Open the ELiXSIR dossier →",
    ctaHref: "/codes/elixsir",
  },
];

export default function ResearchPage() {
  return (
    <main id="main">
      <header className="page-intro shell">
        <p className="kicker">Research atlas</p>
        <h1>Cosmic history,<br />read at many scales.</h1>
        <p>
          Two connected tracks: cosmology across cosmic history, and interdisciplinary
          inference where the same numerical ideas meet other complex systems.
        </p>
        <nav className="research-track-nav" aria-label="Research tracks">
          <a href="#cosmology"><span>I / Cosmology</span><strong>From inflation to present-day structure</strong></a>
          <a href="#interdisciplinary"><span>II / Interdisciplinary</span><strong>Inference across complex systems</strong></a>
        </nav>
        <nav className="anchor-index" aria-label="Research sections">
          {sections.map((section) => (
            <a href={`#${section.id}`} key={section.id}>{section.number} {section.title}</a>
          ))}
        </nav>
      </header>

      <div className="research-sections">
        <header className="research-track-heading shell" id="cosmology">
          <span>I</span><div><p className="kicker">Primary programme</p><h2>Cosmology</h2></div>
        </header>
        {sections.slice(0, 4).map((section, index) => (
          <ResearchChapter section={section} index={index} key={section.id} />
        ))}
        <header className="research-track-heading research-track-heading--orange shell" id="interdisciplinary">
          <span>II</span><div><p className="kicker">Methods across fields</p><h2>Interdisciplinary</h2></div>
        </header>
        {sections.slice(4).map((section, index) => (
          <ResearchChapter section={section} index={index + 4} key={section.id} />
        ))}
      </div>

      <section className="closing-note shell">
        <a className="text-link" href={sitePath("/codes")}>Continue to computational work →</a>
      </section>
    </main>
  );
}

function ResearchChapter({ section, index }: { section: (typeof sections)[number]; index: number }) {
  return (
    <section className="research-chapter shell" id={section.id}>
      <div className="research-chapter__copy">
        <p className="chapter-number">{section.number} / 05</p>
        <p className="kicker">{section.eyebrow}</p>
        <h2>{section.title}</h2>
        {section.text.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
        <a className="text-link" href={sitePath(section.ctaHref)}>{section.cta}</a>
      </div>
      <div className={`research-figure ${index % 2 ? "research-figure--quiet" : ""}`}>
        <figure className="figure-plate">
          <div className="figure-plate__meta">
            <span>FIG. {section.number}</span><span>{section.source}</span>
          </div>
          <div className="research-figure__image">
            <img src={sitePath(section.image)} alt={section.alt} />
          </div>
          <figcaption>
            {section.caption}{" "}
            <a href={section.paper} rel="noreferrer" target="_blank">Paper &amp; figure source ↗</a>
          </figcaption>
        </figure>
        {section.supplementaryFigures.length > 0 && (
          <div className="research-figure-strip" aria-label="Additional figures from related papers">
            {section.supplementaryFigures.map((figure) => (
              <a
                className="research-figure-strip__item"
                href={figure.paper}
                key={figure.label}
                rel="noreferrer"
                target="_blank"
              >
                <div className="research-figure-strip__meta">
                  <span>{figure.label}</span><span>{figure.source}</span>
                </div>
                <div className="research-figure-strip__image">
                  <img src={sitePath(figure.image)} alt={figure.alt} />
                </div>
                <div className="research-figure-strip__caption">
                  <strong>{figure.title}</strong>
                  <span>{figure.caption} Open paper ↗</span>
                </div>
              </a>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}
